[package]
name = "pusher-platform-rust"
version = "0.1.0"
authors = ["Hamilton Chapman <hamchapman@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
jsonwebtoken = "5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
