[package]
name = "pusher_platform_rust"
version = "0.1.0"
authors = ["Hamilton Chapman <hamchapman@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
jsonwebtoken = "5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
erased-serde = "0.3"

[[example]]
name = "generate_access_token"
